### ISSUE TITLE
PasswordType doesn't work when used with plaintext

### ISSUE THREAD

**Issue by mehcode** [kvesteri/sqlalchemy-utils#120]
``` python
AttributeError: type object 'plaintext' has no attribute 'checksum_size'
```

**Comment by ginoledesma** [comment]
The error is misleading, but this is a side-effect of declaring a column using PasswordType without specifying max_length. For example:

```python
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from sqlalchemy_utils.types.password import PasswordType

app = Flask(__name__)
db = SQLAlchemy(app)

class User(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(40), unique=True)
    password = db.Column(PasswordType(
        schemes=[
            'bcrypt',
            'plaintext',
        ],
        deprecated=['plaintext'],
#        max_length=32,
    )) 
```

Output:
```
Traceback (most recent call last):
  File "testit.py", line 8, in <module>
    class User(db.Model):
  File "testit.py", line 16, in User
    deprecated=['plaintext'],
  File "/Users/gledesma/Library/Python/2.7/lib/python/site-packages/sqlalchemy_utils/types/password.py", line 135, in __init__
    max_length = self.calculate_max_length()
  File "/Users/gledesma/Library/Python/2.7/lib/python/site-packages/sqlalchemy_utils/types/password.py", line 153, in calculate_max_length
    scheme.checksum_size
AttributeError: type object 'plaintext' has no attribute 'checksum_size'
```

If you specify `max_length` as a property of `db.column()`, your error goes away.

**Comment by kurtmckee** [comment]
Copying the provided code into the test suite demonstrates that the `AttributeError` is no longer getting triggered. I'm closing this ticket because it doesn't appear to be relevant anymore.
