### ISSUE TITLE
drop_database doesn't quote database name

### ISSUE THREAD

**Issue by jpvanhal** [kvesteri/sqlalchemy-utils#122]
```pytb
Traceback (most recent call last):
  File "/Users/janne/.local/bin/stellar", line 9, in <module>
    load_entry_point('stellar==0.4.2', 'console_scripts', 'stellar')()
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/stellar/command.py", line 264, in main
    stellar()
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/click/core.py", line 572, in __call__
    return self.main(*args, **kwargs)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/click/core.py", line 552, in main
    rv = self.invoke(ctx)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/click/core.py", line 893, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/click/core.py", line 744, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/click/core.py", line 388, in invoke
    return callback(*args, **kwargs)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/stellar/command.py", line 128, in restore
    app.restore(snapshot)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/stellar/app.py", line 155, in restore
    self.operations.remove_database(table.table_name)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/stellar/operations.py", line 111, in remove_database
    get_engine_url(raw_conn, database)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy_utils/functions/database.py", line 267, in drop_database
    engine.execute(text)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1690, in execute
    return connection.execute(statement, *multiparams, **params)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 719, in execute
    return self._execute_text(object, multiparams, params)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 868, in _execute_text
    statement, parameters
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 954, in _execute_context
    context)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 1116, in _handle_dbapi_exception
    exc_info
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/base.py", line 947, in _execute_context
    context)
  File "/Users/janne/.local/venvs/stellar/lib/python2.7/site-packages/sqlalchemy/engine/default.py", line 435, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (ProgrammingError) syntax error at or near "-"
LINE 1: DROP DATABASE foo-bar
```

**Comment by kvesteri** [comment]
Fixed as of 0.29.3
