### ISSUE TITLE
setting `generic_relationship` results in `AttributeError`

### ISSUE THREAD

**Issue by bouzlibop** [kvesteri/sqlalchemy-utils#139]
Hello,

I've bumped into a problem with **generic_relationship** while switching from version `0.9.9` to `1.0.0` of `SQLAlchemy`. Basically to reproduce one can use the first example from http://sqlalchemy-utils.readthedocs.org/en/latest/generic_relationship.html 

Would you have any advices regarding what can be the problem here?

Here is a trace:
> Traceback (most recent call last):
  File "test_error.py", line 12, in <module>
    class Event(db.Model):
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/flask_sqlalchemy/__init__.py", line 536, in __init__
    DeclarativeMeta.__init__(self, name, bases, d)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/api.py", line 55, in __init__
    _as_declarative(cls, classname, cls.__dict__)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 88, in _as_declarative
    _MapperConfig.setup_mapping(cls, classname, dict_)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 103, in setup_mapping
    cfg_cls(cls_, classname, dict_)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 135, in __init__
    self._early_mapping()
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 138, in _early_mapping
    self.map()
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/ext/declarative/base.py", line 530, in map
    **self.mapper_args
  File "<string>", line 2, in mapper
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 627, in __init__
    self._configure_properties()
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1284, in _configure_properties
    self._configure_property(key, prop, False)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy/orm/mapper.py", line 1607, in _configure_property
    prop.instrument_class(self)
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy_utils/generic.py", line 173, in instrument_class
    comparator=self.Comparator(self, mapper),
  File "/home/bouzlibop/.virtualenvs/invenio/local/lib/python2.7/site-packages/sqlalchemy_utils/generic.py", line 144, in __init__
    self._parentmapper = parentmapper
AttributeError: can't set attribute

**Comment by pmarti** [comment]
:+1:

**Comment by bouzlibop** [comment]
Start working for me with the above referenced fix. Thanks for that! :beer: 
When do you plan to release new version containing this fix?

**Comment by kvesteri** [comment]
Hopefully today, there are still some issues with SA 1.0 support.

**Comment by kvesteri** [comment]
Fixed in 0.30.1

**Comment by bouzlibop** [comment]
Thanks! Really appreciate your prompt :zap: reaction.
