### ISSUE TITLE
ImportError: No module named psycopg2

### ISSUE THREAD

**Issue by scorphus** [kvesteri/sqlalchemy-utils#146]
Latest changes seem broken:

    Traceback (most recent call last):
      [snip]
        from wtforms_alchemy import model_form_factory
      File ".../lib/python2.7/site-packages/wtforms_alchemy/__init__.py", line 13, in <module>
        from wtforms_components import (
      File ".../lib/python2.7/site-packages/wtforms_components/__init__.py", line 2, in <module>
        from .fields import (
      File ".../lib/python2.7/site-packages/wtforms_components/fields/__init__.py", line 24, in <module>
        from .phone_number import PhoneNumberField
      File ".../lib/python2.7/site-packages/wtforms_components/fields/phone_number.py", line 3, in <module>
        from sqlalchemy_utils import PhoneNumber
      File ".../sqlalchemy-utils/sqlalchemy_utils/__init__.py", line 58, in <module>
        from .types import (  # noqa
      File ".../sqlalchemy-utils/sqlalchemy_utils/types/__init__.py", line 16, in <module>
        from .pg_composite import (  # noqa
      File ".../sqlalchemy-utils/sqlalchemy_utils/types/pg_composite.py", line 96, in <module>
        import psycopg2
    ImportError: No module named psycopg2
    make: *** [run_server] Error 1

Moving `psycopg2>=2.5.1` from `extras_require` to `install_requires` fixes this issue but that in turn depends on `pg_config` being available.

**Comment by pypingou** [comment]
This is the follow-up of https://github.com/kvesteri/sqlalchemy-utils/issues/145

**Comment by scorphus** [comment]
Thanks!
