### ISSUE TITLE
URLType and Python 3.x

### ISSUE THREAD

**Issue by bodgit** [kvesteri/sqlalchemy-utils#186]
If I try and use `URLType` and Python 3.x I get this when I try and access the object:

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 71, in <listcomp>
    rows = [proc(row) for row in fetch]
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 379, in _instance
    instance = session_identity_map.get(identitykey)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/identity.py", line 146, in get
    if key not in self._dict:
TypeError: unhashable type: 'furl'
```

If I use Python 2.7 then I don't get this problem. From a bit of googling it seems implementing a `__hash__` method might fix this so I've tried to do this as a workaround:

```python
class MyURLType(URLType):
    def __hash__(self):
        return hash(self.url)
```

But that doesn't work and I'm not entirely sure how I get at the furl object.

**Comment by bodgit** [comment]
I managed to get things working with the following:

```python
from sqlalchemy_utils import URLType
from furl import furl

def furl_hash(self):
    return hash(self.url)

furl.__hash__ = furl_hash

class Foo(Model):
    url = Column(URLType)
    ...
```

Basically monkeypatching the furl class with a `__hash__` method. This make me think this is more likely a bug in the furl module rather than your code. If you agree, please let me know and I'll raise an issue in that project instead.

**Comment by kvesteri** [comment]
Yep, this seems to be a problem with ``furl`` not SA-Utils.
