### ISSUE TITLE
PasswordType can't be pickled

### ISSUE THREAD

**Issue by pablogamboa** [kvesteri/sqlalchemy-utils#187]
When trying to pickle an instance of a model that uses PasswordType the following error is thrown:

```
>>> user = User.get(2)
>>> cache.set('foo', user)

Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/Users/pablo/.virtualenvs/drop/lib/python2.7/site-packages/flask_cache/__init__.py", line 200, in set
    self.cache.set(*args, **kwargs)
  File "/Users/pablo/.virtualenvs/drop/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 607, in set
    dump = self.dump_object(value)
  File "/Users/pablo/.virtualenvs/drop/lib/python2.7/site-packages/werkzeug/contrib/cache.py", line 578, in dump_object
    return b'!' + pickle.dumps(value)
  File "/Users/pablo/.virtualenvs/drop/bin/../lib/python2.7/copy_reg.py", line 70, in _reduce_ex
    raise TypeError, "can't pickle %s objects" % base.__name__
TypeError: can't pickle function objects
```

**Comment by kurtmckee** [comment]
Closing because Python 2.7 is no longer supported, and due to lack of activity.
