### ISSUE TITLE
furl objects as dictionary keys

### ISSUE THREAD

**Issue by gruns** [kvesteri/sqlalchemy-utils#191]
It appears SQLAlchemy-Utils furl objects are stored as dictionary keys. In
Python 3, this raises an exception because furl objects are mutable and thus
unhashable.

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/query.py", line 2588, in all
    return list(self)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 86, in instances
    util.raise_from_cause(err)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 189, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=exc_value)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/util/compat.py", line 183, in reraise
    raise value
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 71, in instances
    rows = [proc(row) for row in fetch]
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 71, in <listcomp>
    rows = [proc(row) for row in fetch]
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/loading.py", line 379, in _instance
    instance = session_identity_map.get(identitykey)
  File ".../venv-3.5/lib/python3.5/site-packages/sqlalchemy/orm/identity.py", line 146, in get
    if key not in self._dict:
TypeError: unhashable type: 'furl'
```

See https://github.com/gruns/furl/issues/59.

A potentially simple solution would be to wrap the dictionary with a thin shim
that serializes and deserializes furl objects to their URL strings on insertion
and back on retrieval. At first glance, it appears
sqlalchemy_utils/types/url.py:URLType attempts something similar.

**Comment by kvesteri** [comment]
Hi, this exception comes from SQLAlchemy itself. It is due to a fact that column types used as primary keys should be immutable.

**Comment by gruns** [comment]
The underlying issue in https://github.com/gruns/furl/issues/59 was resolved. Closing.

Thank you for your time and input Konsta.
