### ISSUE TITLE
Test failure in 0.32.11

### ISSUE THREAD

**Issue by daym** [kvesteri/sqlalchemy-utils#256]
I get a test failure with sqlalchemy-utils 0.32.11 and sqlalchemy-1.0.12 and Python 3.5.2:

```
writing SQLAlchemy_Utils.egg-info/PKG-INFO
reading manifest file 'SQLAlchemy_Utils.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no previously-included files matching '*.pyc' found under directory 'tests'
warning: no previously-included files matching '*.pyc' found under directory 'docs'
no previously-included directories found matching 'docs/_build'
warning: no previously-included files found matching 'docs/_themes/.git'
writing manifest file 'SQLAlchemy_Utils.egg-info/SOURCES.txt'
running build_ext
Traceback (most recent call last):
  File "setup.py", line 95, in <module>
    'Topic :: Software Development :: Libraries :: Python Modules'
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 159, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 140, in with_project_on_sys_path
    func()
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 180, in run_tests
    testRunner=self._resolve_as_ep(self.test_runner),
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/main.py", line 93, in __init__
    self.parseArgs(argv)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/main.py", line 123, in parseArgs
    self._do_discovery([])
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/main.py", line 228, in _do_discovery
    self.test = loader.discover(self.start, self.pattern, self.top)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/loader.py", line 341, in discover
    tests = list(self._find_tests(start_dir, pattern))
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/loader.py", line 398, in _find_tests
    full_path, pattern, namespace)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/loader.py", line 475, in _find_test_path
    tests = self.loadTestsFromModule(package, pattern=pattern)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/loader.py", line 190, in loadTestsFromName
    return self.loadTestsFromModule(obj)
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/site-packages/setuptools/command/test.py", line 38, in loadTestsFromModule
    tests.append(self.loadTestsFromName(submodule))
  File "/gnu/store/r4dkdickrr6fpkxcwwxlbriva2c8cx2s-python-3.5.2/lib/python3.5/unittest/loader.py", line 204, in loadTestsFromName
    test = obj()
  File "/tmp/guix-build-python-sqlalchemy-utils-0.32.11.drv-0/SQLAlchemy-Utils-0.32.11/sqlalchemy_utils/relationships/chained_join.py", line 5, in chained_join
    property_ = relationships[0].property
IndexError: tuple index out of range
phase `check' failed after 2.4 seconds
builder for `/gnu/store/6nxygyj17frv3aj0msi3ymlbqf5kznf8-python-sqlalchemy-utils-0.32.11.drv' failed with exit code 1
cannot build derivation `/gnu/store/6xgarrjq4dbpvhz1sk0x4zp9vhx0khiw-python-platinum-0.0.1-28f5dcc.drv': 1 dependencies couldn't be built
guix environment: error: build failed: build of `/gnu/store/6xgarrjq4dbpvhz1sk0x4zp9vhx0khiw-python-platinum-0.0.1-28f5dcc.drv' failed
```

**Comment by daym** [comment]
Updating SQLAlchemy to 1.0.16 didn't help either.
