### ISSUE TITLE
CompositeType example doesn't work

### ISSUE THREAD

**Issue by jo2y** [kvesteri/sqlalchemy-utils#319]
Below is the example from pg_composite.py with a few extra pieces to fill in the gaps. On the pgsql side, I ran this, but I don't think the code gets that far to matter exactly how money_type is defined.
CREATE TYPE money_type AS (currency text, amount int);

It looks like Account is being replaced in the sqlalchemy.orm machinery and losing it's specialness. (Or I'm using it wrong.)

import sqlalchemy as sa
from sqlalchemy_utils import CompositeType, CurrencyType, register_composites
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy.orm import sessionmaker
from sqlalchemy import create_engine

_uri = ('postgresql+psycopg2://<snip>')

_engine = create_engine(_uri)
_conn = _engine.connect()

Base = declarative_base()
Session = sessionmaker()

class Account(Base):
    __tablename__ = 'account'
    id = sa.Column(sa.Integer, primary_key=True)
    balance = sa.Column(
        CompositeType(
            'money_type',
            [
                sa.Column('currency', CurrencyType),
                sa.Column('amount', sa.Integer)
            ]
        )
    )

register_composites(_conn)
session = Session()
session.query(Account).filter(Account.balance.amount > 5000)

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python2.7/dist-packages/sqlalchemy/orm/attributes.py", line 193, in __getattr__
    key)
AttributeError: Neither 'InstrumentedAttribute' object nor 'Comparator' object associated with Account.balance has an attribute 'amount'

**Comment by jo2y** [comment]
@kvesteri 

I believe I fixed this. Printing the generated query on the last line, I get this:
```
SELECT account.id, account.balance 
FROM account 
WHERE (account.balance).amount > %(param_1)s
```

The problem was this line in pg_composite.py. `type_ = self.type.typemap[key]`.
self.type.typemap doesn't exist, so the try/except was catching that error just as if key didn't exist in typemap.

**Comment by olegpidsadnyi** [comment]
@jo2y i'm getting max recursion depth with this change

**Comment by mrquokka** [comment]
May be you need somethink like that
p.s. commented block need to first start
```
engine = sqlalchemy.create_engine(
    'postgresql+psycopg2://' +
    postgresql_config['db_login'] + ':' +
    postgresql_config['db_password'] + '@' +
    postgresql_config['db_remote_adress'] + ':' +
    str(postgresql_config['db_remote_port']) + '/' +
    postgresql_config['db_name'],

    echo=postgresql_config['db_echo'],
    isolation_level=postgresql_config['db_isolation_level'],
    pool_size=20, max_overflow=0)

engine.execute("SET TIME ZONE 0")
connection = engine.connect()
Base = sqlalchemy.ext.declarative.declarative_base()


def get_comp_type():
  child = CompositeType(
      'type_1', [
          sqlalchemy.Column('test_str', sqlalchemy.String),
          sqlalchemy.Column('amount', sqlalchemy.Integer)
      ]
  )
  # return child
  parent = CompositeType(
      'type_2', [
          sqlalchemy.Column('test_str', sqlalchemy.String),
          sqlalchemy.Column('amount', sqlalchemy.Integer),
          sqlalchemy.Column('child_compound', child)
      ]
  )
  return parent


class Account(Base):
  __tablename__ = 'account'
  id = sqlalchemy.Column(sqlalchemy.Integer, primary_key=True)
  balance = sqlalchemy.Column(get_comp_type())

# Base.metadata.create_all(engine)

session = sqlalchemy.orm.scoped_session(sqlalchemy.orm.sessionmaker(
    bind=connection, autoflush=False))

register_composites(connection)
# session.add(Account(id=2, balance=(10, '232', (33, '228'))))
# session.commit()
```

**Comment by olirice** [comment]
confirmed that:
- Filtering on a column within a composite as shown in documentation results in AttributeError
- PR #323 introduces a recursion exception

**Comment by emma-46** [comment]
I had the same issue as wellm, is there any new lead to fix it ? I confirm as well that https://github.com/kvesteri/sqlalchemy-utils/pull/323 doesn't work.

**Comment by rickemery** [comment]
I am also having this issue. Is there any work-around that allows querying of CompositeTypes?

**Comment by olirice** [comment]
> I am also having this issue. Is there any work-around that allows querying of CompositeTypes?

The stock sqla method has improved https://docs.sqlalchemy.org/en/13/orm/composites.html#composite-column-types

but if you want something as declarative as the example in sqlalchemy_utils docs, you'll have to roll your own afaik

This was my work around:

```python3
from __future__ import annotations

from collections import namedtuple
from typing import List, NamedTuple, Type

from sqlalchemy import Column
from sqlalchemy.sql.type_api import TypeEngine
from sqlalchemy.types import UserDefinedType


class CompositeType(UserDefinedType):
    """
    Represents a PostgreSQL composite type.
    :param name:
        Name of the composite type.
    :param columns:
        List of columns that this composite type consists of
    """

    python_type = tuple

    name: str
    columns: List[Column] = []
    type_cls: Type[NamedTuple]

    def init(self, *args, **kwargs):
        pass

def composite_type_factory(name: str, columns: List[Column]) -> TypeEngine:
    """Factory for creating PostgreSQL composite types"""

    for column in columns:
        column.key = column.name

    type_cls: Type[NamedTuple] = namedtuple(name, [c.name for c in columns])

    composite = type(
        name,
        (CompositeType,),
        {
            "name": name,
            "columns": columns,
            "type_cls": type_cls,
        },
    )
    return composite
```

`composite_type_factory` exposes the same interface as the sqlalchemy_utils `CompositeType`.

e.g.

```python3
class Account(Base):

    __tablename__ = 'account'

    id = sa.Column(sa.Integer, primary_key=True)

    balance = sa.Column(
        composite_type_factory(
            'money_type',
            [
                sa.Column('currency', CurrencyType),
                sa.Column('amount', sa.Integer)
            ]
        )
    )

```

**Comment by andruli** [comment]
All,

In case you are still waiting for a solution I just tuned @jo2y 's solution to fix the recursion problem. This is a working solution:

```python
from sqlalchemy_utils import CompositeType
from sqlalchemy_utils.types.pg_composite import CompositeElement

class _CompositeType(CompositeType):
    class comparator_factory(CompositeType.comparator_factory):
        def __getattr__(self, key):
            try:
                type_ = self.type.typemap[key]
            except KeyError:
                raise KeyError(
                    "Type '%s' doesn't have an attribute: '%s'" % (
                        object.__getattribute__(self, 'name'), key
                    )
                )

            return CompositeElement(self.expr, key, type_)

    def __init__(self, *args, **kwargs) -> None:
        super().__init__(*args, **kwargs)

        self.typemap = dict((col.name, col.type) for col in self.columns)
```

Then you can just use `_CompositeType` instead of `CompositeType` and your SQLAlchemy code will be able to access the properties of your compound type.

```
>>> cdp_segments.CDPSegment.event_recency.operator
<sqlalchemy_utils.types.pg_composite.CompositeElement at 0x7f48df073e50; operator>
```
