### ISSUE TITLE
Latest sqlalchemy beta removes `_literal_as_text`

### ISSUE THREAD

**Issue by pazembrz** [kvesteri/sqlalchemy-utils#383]
sqlalchemy-utils are failing with latest (beta) sqlalchemy:
```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/src/invenio-db/invenio_db/__init__.py", line 93, in <module>
    from .ext import InvenioDB
  File "/home/src/invenio-db/invenio_db/ext.py", line 18, in <module>
    from sqlalchemy_utils.functions import get_class_by_table
  File "/home/envs/db/src/sqlalchemy-utils/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/home/envs/db/src/sqlalchemy-utils/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/home/envs/db/src/sqlalchemy-utils/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/home/envs/db/src/sqlalchemy-utils/sqlalchemy_utils/functions/database.py", line 13, in <module>
    from ..expressions import explain_analyze
  File "/home/envs/db/src/sqlalchemy-utils/sqlalchemy_utils/expressions.py", line 4, in <module>
    from sqlalchemy.sql.expression import (
ImportError: cannot import name '_literal_as_text'
```

**Comment by seperman** [comment]
I'm on `sqlalchemy==1.3.10` and running into this issue. It is a stable release of sqlalchemy.

**Comment by kvesteri** [comment]
Fixed. Unfortunately had to remove functions explain and explain_analyze as a result.
