### ISSUE TITLE
Using `database_exists` on a non-existent SQL Server database throws InterfaceError.

### ISSUE THREAD

**Issue by yaseen-mowzer-hexagon** [kvesteri/sqlalchemy-utils#423]
Using `database_exists` on a non-existent SQL Server database throws an exception.

- I'm using version 0.36.1
- I'm using sqlalchemy version 1.3.13
- This issue exists on both Python 2 and Python 3
- Using the `ODBC Driver 17 for SQL Server`
- If the database exists an error is not thrown

``` python
import sqlalchemy_utils
import sqlalchemy

print("sqlalchemy_utils VERSION", sqlalchemy_utils.__version__)
print("sqlalchemy VERSION", sqlalchemy.__version__)

existing_db = "mssql+pyodbc://localhost/empty-project-2?driver=ODBC Driver 17 for SQL Server"
exists = sqlalchemy_utils.database_exists(existing_db)
print("DB exists:", exists)

non_existent_db = "mssql+pyodbc://localhost/non-exist?driver=ODBC Driver 17 for SQL Server"
not_exists = sqlalchemy_utils.database_exists(non_existent_db)
print("DB does not exist:", not_exists)
```

Expected output:

```
sqlalchemy_utils VERSION 0.36.1
sqlalchemy VERSION 1.3.13
DB exists:  True
DB does not exist: False
```

Actual Output:

```
sqlalchemy_utils VERSION 0.36.1
sqlalchemy VERSION 1.3.13
DB exists: True
Traceback (most recent call last):
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "<pythondir>\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "<pythondir>\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)
pyodbc.InterfaceError: ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'DESKTOP-MH50HBK\\yaseenm\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "non-exist" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'DESKTOP-MH50HBK\\yaseenm\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "non-exist" requested by the login. The login failed. (4060)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:/Users/yaseenm/.PyCharm2019.3/config/scratches/scratch.py", line 12, in <module>
    not_exists = sqlalchemy_utils.database_exists(non_existent_db)
  File "<pythondir>\lib\site-packages\sqlalchemy_utils\functions\database.py", line 424, in database_exists
    result = engine.execute(text)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 2181, in execute
    connection = self._contextual_connect(close_with_result=True)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 2242, in _contextual_connect
    self._wrap_pool_connect(self.pool.connect, None),
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 2279, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 1547, in _handle_dbapi_exception_noconnection
    util.raise_from_cause(sqlalchemy_exception, exc_info)
  File "<pythondir>\lib\site-packages\sqlalchemy\util\compat.py", line 398, in raise_from_cause
    reraise(type(exception), exception, tb=exc_tb, cause=cause)
  File "<pythondir>\lib\site-packages\sqlalchemy\util\compat.py", line 152, in reraise
    raise value.with_traceback(tb)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\base.py", line 2276, in _wrap_pool_connect
    return fn()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 363, in connect
    return _ConnectionFairy._checkout(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 773, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 492, in checkout
    rec = pool._do_get()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\impl.py", line 139, in _do_get
    self._dec_overflow()
  File "<pythondir>\lib\site-packages\sqlalchemy\util\langhelpers.py", line 68, in __exit__
    compat.reraise(exc_type, exc_value, exc_tb)
  File "<pythondir>\lib\site-packages\sqlalchemy\util\compat.py", line 153, in reraise
    raise value
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\impl.py", line 136, in _do_get
    return self._create_connection()
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 308, in _create_connection
    return _ConnectionRecord(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 437, in __init__
    self.__connect(first_connect_check=True)
  File "<pythondir>\lib\site-packages\sqlalchemy\pool\base.py", line 652, in __connect
    connection = pool._invoke_creator(self)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\strategies.py", line 114, in connect
    return dialect.connect(*cargs, **cparams)
  File "<pythondir>\lib\site-packages\sqlalchemy\engine\default.py", line 489, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlalchemy.exc.InterfaceError: (pyodbc.InterfaceError) ('28000', '[28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'DESKTOP-MH50HBK\\yaseenm\'. (18456) (SQLDriverConnect); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "non-exist" requested by the login. The login failed. (4060); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Login failed for user \'DESKTOP-MH50HBK\\yaseenm\'. (18456); [28000] [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]Cannot open database "non-exist" requested by the login. The login failed. (4060)')
(Background on this error at: http://sqlalche.me/e/rvf5)

```

**Comment by lengthmin** [comment]
A workaround:


```python
from sqlalchemy.exc import InterfaceError

def database_exists_(url):
    try:
        return database_exists(url)
    except InterfaceError:
        return False
```
