### ISSUE TITLE
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py) 

### ISSUE THREAD

**Issue by FelixBenning** [kvesteri/sqlalchemy-utils#502]
It appears that version 1.4 will break sqlalchemy-utils

```python
>>> import sqlalchemy
>>> import sqlalchemy_utils
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/__init__.py", line 1, in <module>
    from .aggregates import aggregated  # noqa
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/aggregates.py", line 372, in <module>
    from .functions.orm import get_column_key
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/__init__.py", line 1, in <module>
    from .database import (  # noqa
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/database.py", line 11, in <module>
    from .orm import quote
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_utils/functions/orm.py", line 14, in <module>
    from sqlalchemy.orm.query import _ColumnEntity
ImportError: cannot import name '_ColumnEntity' from 'sqlalchemy.orm.query' (/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/query.py)
>>> sqlalchemy.__version__
'1.4.0b3'
```

see also https://github.com/sqlalchemy/sqlalchemy/issues/6000

**Comment by FelixBenning** [comment]
#474 sorry for the duplicate
