### ISSUE TITLE
database_exists function for oracle db fails

### ISSUE THREAD

**Issue by visuman** [kvesteri/sqlalchemy-utils#627]
The following code is failing with the error:
```
>>> from  sqlalchemy_utils import database_exists
>>> database_exists('oracle://test:test@test_oracle_host/dev')
Traceback (most recent call last):
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
cx_Oracle.DatabaseError: ORA-00923: FROM keyword not found where expected

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/venv39/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 513, in database_exists
    return bool(_get_scalar_result(engine, sa.text(text)))
  File "/venv39/lib/python3.9/site-packages/sqlalchemy_utils/functions/database.py", line 443, in _get_scalar_result
    return conn.scalar(sql)
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1188, in scalar
    return self.execute(object_, *multiparams, **params).scalar()
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1306, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/sql/elements.py", line 332, in _execute_on_connection
    return connection._execute_clauseelement(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1498, in _execute_clauseelement
    ret = self._execute_context(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1862, in _execute_context
    self._handle_dbapi_exception(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2043, in _handle_dbapi_exception
    util.raise_(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 208, in raise_
    raise exception
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 1819, in _execute_context
    self.dialect.do_execute(
  File "/venv39/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 732, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.DatabaseError: (cx_Oracle.DatabaseError) ORA-00923: FROM keyword not found where expected
[SQL: SELECT 1]
(Background on this error at: https://sqlalche.me/e/14/4xp6)
```

Seems like oracle does not support  `SELECT 1 `

**Comment by kurtmckee** [comment]
@visuman Thanks for reporting this! I have a possible fix posted in #628, though I cannot test this myself because I don't have access to an Oracle database.

Would you test the code in that PR against various scenarios and let me know whether this resolves the crash you're seeing? Some sample scenarios are listed in the PR, but you may know of other possibilities. Thanks!
