### ISSUE TITLE
0.42.2: documentation build fails with sphinx 8.x

### ISSUE THREAD

**Issue by kloczek** [kvesteri/sqlalchemy-utils#749]
```console
+ /usr/bin/sphinx-build -n -T -b man docs build/sphinx/man
Running Sphinx v8.0.2
loading translations [en]... done
making output directory... done
WARNING: html_static_path entry '_static' does not exist
Converting `source_suffix = '.rst'` to `source_suffix = {'.rst': 'restructuredtext'}`.
ERROR: Invalid value `None` in intersphinx_mapping['https://docs.python.org/3/']. Expected a two-element tuple or list.

Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/sphinx/cmd/build.py", line 332, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.10/site-packages/sphinx/application.py", line 277, in __init__
    self.events.emit('config-inited', self.config)
  File "/usr/lib/python3.10/site-packages/sphinx/events.py", line 100, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/lib/python3.10/site-packages/sphinx/ext/intersphinx/_load.py", line 127, in validate_intersphinx_mapping
    raise ConfigError(msg)
sphinx.errors.ConfigError: Invalid `intersphinx_mapping` configuration (1 error).

Configuration error:
Invalid `intersphinx_mapping` configuration (1 error).
```

**Comment by kurtmckee** [comment]
Docs are building now but need additional work.
